-define(PROTOIDENUM, [{1, request_account_enter}, {6, request_insert_name}, {5, request_create_alliance}, {2, ok}, {3, fail}, {4, new_user_name}]). 
-define(PROTONAMEENUM, [{request_account_enter, 1}, {request_insert_name, 6}, {request_create_alliance, 5}, {ok, 2}, {fail, 3}, {new_user_name, 4}]). 
