request_account_enter:1
    account:string
    password:string
request_user_infos:
    #empty
request_item_infos:
    #empty
request_remote_user_info:
    uuid:string
account_enter_ret:2
    error_code:string
user:
    uuid:string
    name:string
    level:integer
users:
    user:array-user
item:
    uuid:string
    name:string
    amount:integer
items:
    user:user
    other:string
    item:array-item